import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import DashboardWrapper from "./DashboardWrappe";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DashboardWrapper> {children}</DashboardWrapper>
      </body>
    </html>
  );
}
